driver:
  name: terraform
  root_module_directory: test/fixtures

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
  - name: local
    backend: gcp

platforms:
  - name: gcp

suites:
  - name: http_triggered_function
    driver:
      root_module_directory: test/fixtures/http_event
  - name: event_triggered_function
    driver:
      root_module_directory: test/fixtures/storage_event
